version: "3.7"

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v21.2
    container_name: cockroach
    volumes:
      - cockroach:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8082:8080
    restart: always
    command: start-single-node --insecure
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb:0.11.9
    ports: 
      - "8083:8081" 
    links: 
      - cockroach:cockroach 
    environment:
      - DATABASE_URL=postgres://root:root@cockroach:26257/postgres?sslmode=disable
    depends_on:
      - cockroach
  minio:
    image: minio/minio:RELEASE.2021-10-23T03-28-24Z
    container_name: minio
    volumes:
      - miniodata:/data
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root1234
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  cockroach:
  miniodata:
