version: "3.7"

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v21.2
    container_name: cockroach
    volumes:
      - cockroach:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8082:8080
    restart: always
    command: start-single-node --insecure
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb:0.11.9
    ports: 
      - "8083:8081" 
    links: 
      - cockroach:cockroach 
    environment:
      - DATABASE_URL=postgres://root:root@cockroach:26257/postgres?sslmode=disable
    depends_on:
      - cockroach
volumes:
  cockroach:
