version: "3.7"

services:
  api-example:
    image: danielarmasjuarez/api-example:v0.1.1
    container_name: api
    ports:
      - 22210:22210
      - 8888:8888
    restart: always
    environment:
      DB_USER: root               
      DB_PASSWORD: root            
      DB_DATABASE: postgres
      DB_PORT: 26257             
      DB_HOST: cockroach               
      GRPC_API_PORT: 22210
      GRAPHQL_API_PORT: 8888
      PROMETHEUS_PUSHGATEWAY: http://localhost:9091/
      JWT_SECRET: O8pzXjp4QMk4cAD60dHeoOnxdVsDc9
    depends_on:
      - cockroach
  cockroach:
    image: cockroachdb/cockroach:latest-v21.2
    container_name: cockroach
    volumes:
      - cockroach:/cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8082:8080
    restart: always
    command: start-single-node --insecure
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb:0.11.9
    ports: 
      - "8083:8081" 
    links: 
      - cockroach:cockroach 
    environment:
      - DATABASE_URL=postgres://root:root@cockroach:26257/postgres?sslmode=disable
    depends_on:
      - cockroach
volumes:
  cockroach:
