// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID                       *string  `json:"id"`
	Name                     *string  `json:"name"`
	Price                    *float64 `json:"price"`
	HighQualityPhoto         *string  `json:"highQualityPhoto"`
	HighQualityPhotoBlurHash *string  `json:"highQualityPhotoBlurHash"`
	LowQualityPhoto          *string  `json:"lowQualityPhoto"`
	LowQualityPhotoBlurHash  *string  `json:"lowQualityPhotoBlurHash"`
	Thumbnail                *string  `json:"thumbnail"`
	ThumbnailBlurHash        *string  `json:"thumbnailBlurHash"`
	CreateTime               *string  `json:"createTime"`
	UpdateTime               *string  `json:"updateTime"`
	Cursor                   *int     `json:"cursor"`
}

type User struct {
	ID         *string `json:"id"`
	Email      *string `json:"email"`
	CreateTime *string `json:"createTime"`
	UpdateTime *string `json:"updateTime"`
}
